services:
  backend:
    env_file:
      - ./env/backend.env
    secrets:
      - db-password
      - jwt
    build:
      dockerfile: Dockerfile
      context: server
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8880
    ports:
      - "8880:8880"

  db:
    image: postgres:17.2-bookworm
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./env/db.env
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # TODO: add frontend docker image

volumes:
  db-data:

secrets:
  db-password:
    file: ./secrets/db_secret.txt
  jwt:
    file: ./secrets/jwt_secret.txt
